### ISSUE TITLE
k8s plugin - kubectl cluster-info is hard to read

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2892] opened 2019-09-30 17:40 UTC
The output is formatted strangely and hard for a user to read, when using the same command in a mac terminal the output is formatted normal.

KUI returning these appended to the output strings:

`[0;32m`
`[0m`

**Comment by myan9** [comment] 2019-09-30 19:30
Duplicate of https://github.com/IBM/kui/issues/1420

**Closed by myan9** 2019-09-30 19:31 UTC
