### ISSUE TITLE
UX for Semicolon invokes is inconsistent

### ISSUE THREAD

**Issue by subbarao-meduri** [IBM/kui#5260] opened 2020-07-27 15:49 UTC
**Describe the bug**

**Steps to reproduce the behavior**

1. Executed the following commands and got this output

```
In[6]
echo "hello world"; sleep 5; echo "end"
11:46:21 AM

hello world
end
In[7]
sleep 5; echo "end"
11:46:35 AM

ok
```

**Expected behavior**
The second `echo` only produced `ok` output, instead of printing `end`

**System**

- Kui version: 8.11.0
- Operating system: MacOS

**Comment by myan9** [comment] 2020-07-29 20:22
Can you check this bug with the latest version? This should be fixed in latest.

This is what I saw:
![Screen Shot 2020-07-29 at 4 22 30 PM](https://user-images.githubusercontent.com/21212160/88849313-b4c12a80-d1b7-11ea-9f6a-a01eb495ecca.png)

**Comment by myan9** [comment] 2020-07-30 21:20
Thanks! `sleep` is a bit of a red herring here. The problem is that if the command chain starts with a registered kui command,  then the whole command line will be sent to that handler, which means that each command needs to, on its own, handle semicolons. We’ve hacked this in a few places, e.g. ls and echo, but we need to figure out what the real solution is. The same thing holds if the command line includes `|` or `>`. We could hoist the semiInvoke to repl exec, and get rid of the hacks.

**Closed** 2020-08-03 23:14 UTC
Labels: bug
