### ISSUE TITLE
Exec npm ci ; npm run watch:webpack in the unzip souce code meet error

### ISSUE THREAD

**Issue by yixjuan** [IBM/kui#5111] opened 2020-07-10 16:05 UTC
1. Download from this repo，and unzip the souce code
<img width="493" alt="图片" src="https://user-images.githubusercontent.com/68119885/87173908-fffac280-c308-11ea-860a-2051b3ef2a3d.png">
2.run npm ci
<img width="420" alt="图片" src="https://user-images.githubusercontent.com/68119885/87174172-5ff16900-c309-11ea-9e54-3568181cf4a2.png">
<img width="649" alt="图片" src="https://user-images.githubusercontent.com/68119885/87174198-697ad100-c309-11ea-911b-5a48fcd035a8.png">
3.npm run watch:webpack
<img width="950" alt="图片" src="https://user-images.githubusercontent.com/68119885/87174698-279e5a80-c30a-11ea-8676-e64fe60f5ec1.png">
 or
<img width="867" alt="图片" src="https://user-images.githubusercontent.com/68119885/87174779-456bbf80-c30a-11ea-88c1-6441eeb1836d.png">

**Comment by myan9** [comment] 2020-07-10 20:03
Hi @yixjuan! Thanks for the bug report! 

1) You downloaded kui source code instead of `git clone the repo`, so when you `npm ci`, `husky` failed at setting up git hooks. This error doesn't affect building and compiling the project, so that's ok.

2) our script to start proxy assumes the project root directory is named as `kui`, but yours is named as `kui-8.10.12` due to the source code download, so your webpack watcher failed to start proxy. I have pushed a fix for this, but you can also quickly workaround this by changing the project name to `kui` or `git clone the repo`.

3) The last error you had: `Cannot find module ‘marked’` is probably caused by some weird state you had? I can't reproduce this error. Can you re-verify this issue by fixing the second issue and re-building Kui in a clean environment? Thanks!

**Closed** 2020-07-10 21:19 UTC
