### ISSUE TITLE
Theme set via command is not reflected in Settings 

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#5151] opened 2020-07-16 16:43 UTC
**Describe the bug**
Using `themes` command and selecting dark theme and then going to setting page, the dark theme is not selected 

**Steps to reproduce the behavior**

1. Start KUI.  default theme is light
2. Type `themes`
3. select dark theme
4. open the about/settings
5. view the theme setting.  The theme shows light is set, which contradicts the dark setting from the themes command. 

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/32707829/87698076-f9cd7180-c760-11ea-815d-241a1989cb18.png)

**System**

- Kui version: v8.10.13
- Operating system: ACM

**Comment by chrisahl** [comment] 2020-07-16 17:12
FYI @mark-nc

**Comment by starpit** [comment] 2020-07-16 19:08
to make sure i understand fully: you started from scratch, issued themes, switched themes, then clicked the Settings/About, then clicked themes?

i.e. you did not have the settings->themes selected prior to switching themes?

**Comment by chrisahl** [comment] 2020-07-16 19:19
So I retried from brand new KUI in new tab.  And as you note, it did not happen if the Settings/About had not been opened before.   But if I had opened Settings/About and closed it, then did the themes command and switched themes, then open Settings/About again, the bug shows.

**Comment by starpit** [comment] 2020-07-16 19:36
got it, this is helpful clarification. closing the sidecar does not reset the model.

thoughts about #5156 as a way to improve this?

**Comment by mark-nc** [comment] 2020-07-16 19:56
Shouldn't clicking a theme in the themes table (in response to entering the command `themes`) set the same model that is used to display current theme in the sidecar?  And then shouldn't the sidecar, whether previously opened or closed be refreshing the setting from the same model?  Maybe I am misunderstanding, but not sure we need a new UI for that, just making sure there is a common model to refresh both UIs with the current state.  That is the typical way React components work is they refresh their appearance from the current state of the model.

**Comment by starpit** [comment] 2020-07-16 20:14
kui tables currently default to being static tables. this was an intentional choice, to preserve the expected behavior of tables in a terminal -- i.e. they serve as artifacts of the past, and scrolling is a way to time warp into the past. if the user wishes to opt in to watchable tables, they can (if supported by the given controller); e.g. by adding `--watch` for kubectl get commands.

this structure makes less (if any) sense for tables in the sidecar -- which does not have the same scroll-history presentation. 

#5156 proposes lifting the themes table so that it is presented in the terminal.

we may also want to make the themes table watchable by default (no issue for this, yet).

**Comment by mark-nc** [comment] 2020-07-16 20:33
Hmm...good point.  But that may point to a larger issue for settings in general.  Settings should be (I think) session wide so are not really like a static table (historical information), nor are they like a watch table (k8s resources that can change status).  They are their own thing/model that stores current state of the settings for that KUI session.  Is the problem that we are overloading other views intended for other purposes to handle this cases?  Should settings be displayed and managed using a view type specific to them that can work off a common model no matter where they show up in the UI?  Putting a link in the sidecar to run the command solves the issue at the moment, but only because we decided (now) that we always want that in the REPL area.  What if we change our minds in the future and want all settings handled in a separate popup dialog or something like that?

Is this a case where we are trying to use a "hammer" because everything looks like a "nail", to use the old analogy?

**Comment by starpit** [comment] 2020-07-16 20:43
i think the only question here is whether the themes table to support a `--watch` flag (and whether watch should be the default).

Separately, we should determine whether we want to show the themes table in a terminal or the sidecar. Given that the user can opt to show the themes table in a terminal, it might be dissonant to see the same table in two places simultaneously.

**Comment by mark-nc** [comment] 2020-07-16 20:53
I agree that showing it in two places at once is a bit disconcerting.....which is what prompted me to wonder if things like session settings really belong in the terminal or in their own place.  On one hand, you can say that those handful of commands like `themes` are built-in KUI commands, but even with that, there are a variety of built-in KUI commands.  Ones like `help` and `getting started` launch the sidecar to show content.  In this case, `themes` displays a settings configuration control in the terminal.  As there will be other settings available over time, shouldn't they all congregate in one place?

**Comment by starpit** [comment] 2020-07-16 20:56
yeah, the original thought was that we will grow the configuration choices over time. themes is just one... and so presenting these with a hierarchical Navigation framing would allow for Configuration -> Themes, Terminal, ...

but... maybe there's something better we can do here.

**Comment by mark-nc** [comment] 2020-07-16 21:05
@jackiwakin Do you want to weigh in on this topic?

**Comment by starpit** [comment] 2021-01-26 00:30
i believe we are now good here.

**Closed by starpit** 2021-01-26 00:30 UTC

**Comment by mark-nc** [comment] 2021-01-26 14:35
So, @starpit , what was the solution to this?  I see that https://github.com/IBM/kui/issues/5156 was closed as no longer relevant, but there was not mention of another issue or PR that addressed this.  I believe you that it is now fixed, I am just curious as to what the fix was.

**Comment by starpit** [comment] 2021-01-27 00:36
Howdy! Apologies for lack of clarity in my previous comment. The proposed alternative UI for presenting themes is to use the Settings status stripe widget. This widget is responsive. The converse is currently not true, but perhaps it should be (one current principal of Kui states that command output is, unless otherwise requested by the user, intended to be a marker in time, rather than a reflection of current reality).

![theme switching](https://user-images.githubusercontent.com/4741620/105925098-9379b380-600d-11eb-886c-794bba7d9b4a.gif)
